config/routes.rb
Rubricam::Application.routes.draw do

  resources :nodes

  resources :nivarts

  resources :version_comments

  resources :parties

  resources :campagnes

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :users

  root :to => 'accueil#index'
  match '/regles', to: 'accueil#regles'
  match '/fan_art', to: 'accueil#fan_art'
  match '/carte', to: 'accueil#carte'
  match '/navigation', to: 'accueil#navigation'
  match '/cv_elyse_cordeau', to: 'accueil#cv_elyse_cordeau'
  get 'omni_search/search'
  get 'users/omni_search/search'

  resources :arts

  resources :royaumes

  resources :combinaisons

  resources :disciplines

  resources :nivdisciplines

  resources :objets

  resources :routines

  resources :spheres

  resources :lieus

  resources :organisations do
    get :secret_update, on: :member
  end

  resources :historiques

  resources :atouts

  resources :relations do
    get :visuel, on: :collection
  end

  resources :relations_organisations

  resources :capacites

  resources :personnages do
    get :get_infos, on: :collection  #For Ajax test
    get :public_edit, on: :member
    get :public_show, on: :member
    post :public_update, on: :member
    get :routine_edit, on: :member
    post :routine_update, on: :member
    get :discipline_edit, on: :member
    post :discipline_update, on: :member
    get :combinaison_edit, on: :member
    post :combinaison_update, on: :member
    get :pnjs, on: :collection
    get :pjs, on: :collection
    get :reset_xps, on: :member
    get :reset_bonus, on: :member
    get :reset_base, on: :member
    get :background_edit, on: :member
    post :background_update, on: :member
    get :secret_update, on: :member
    get :pnj_update, on: :member
    get :test_update, on: :member
  end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  before_filter :redirect_unauthorized_to_write, :only=> [:edit, :update, :destroy]
  after_filter :redirect_unauthorized_to_read, :only=> [:show]

  # GET /parties
  # GET /parties.json
  def index
    if @user.role == User::ROLE_ADMIN
      @parties = Partie.order(:date).paginate(page: params[:page], per_page: 15)
    else
      @parties = Partie.played_by(@user).paginate(page: params[:page], per_page: 15)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Partie.find(params[:id])
    if @user.role == User::ROLE_ADMIN
      @membres = @party.personnages.group_by{|p| p.pnj }
    else
      @membres = @party.personnages.none_secret.group_by{|p| p.pnj }
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if @user.role != User::ROLE_ADMIN
    @party = Partie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Partie.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create
    # raise "foo"
    @party = Partie.new(params[:partie])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Partie a été crée avec succès.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Partie.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:partie])
        format.html { redirect_to @party, notice: 'Partie a été édité avec succès.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Partie.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  private

  def redirect_unauthorized_to_write
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if !permition_write?(@user)
  end

  def redirect_unauthorized_to_read
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if !permition_read?(@user)
  end

  def permition_read?(user)
    return true if @party.campagne.present? && @party.campagne.users.map{|u| u.id}.include?(user.id)
    return true if user.role == User::ROLE_ADMIN
    false
  end

  def permition_write?(user)
    return true if user.role == User::ROLE_ADMIN
    false
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
  def label_duree(duree)
    if duree < 4
      color = "label-info"
    elsif duree < 6
      color = "label-success"
    elsif duree < 8
      color = "label-success"
    else
      color = "label-danger"
    end
    content_tag :span, "#{duree} heures", class: "label #{color}"
  end
end

app/views/parties/_form.html.erb
<%= simple_form_for(@party) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-5">
    <%= f.input :date %>
    <%= f.input :duree, label: "Durée (heure)" %>
    <%= f.input :nom %>
    <%= f.input :description %>
    <%= f.button :submit, "Créer/Editer une partie", class: 'btn btn-success btn-sm' %>
    <%= link_to 'Retour', parties_path, class: 'btn btn-warning btn-sm' %>
  </div>

  <div class="col-md-5">
    <%= f.input :description_publique %>
    <%= f.input :secret, label: "Voulez-vous que ce cette partie soit secrète ?", wrapper_html: {class: 'inline simple-checkbox'} %>
    <%= f.input :image_lien %>
    <%= f.input :xps %>
    <%= f.input :campagne_id, collection: Campagne.all.map{|c| [c.nom, c.id]} %>
    <div class="user">
      <label for="search_user"> Rechercher user :</label>
      <input id="search_user" type="text" onkeypress="filter(this, '.user .checkbox .check_boxes')" onkeyup="epurationCheckBox(this, '.user .checkbox .check_boxes')">
      <%= f.association(:users, as: :check_boxes, :collection => User.all.map {|c| [c.email, c.id]}.uniq, label: false, wrapper_html: { class: 'col-md-12' }) %>
    </div>
    <%= f.input :notes %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    manageCheckBox("#search_user", ".user .checkbox .check_boxes");
  });
</script>

app/views/parties/edit.html.erb
<h1>Editer une partie</h1>

<%= render 'form' %>

app/views/parties/index.html.erb
<%= link_to 'Nouvelle partie', new_party_path, class: 'btn btn-success btn-sm create-float' %>
<%= link_to 'Retour', root_path, class: 'btn btn-warning btn-sm create-float' %>
<h1>Liste des parties</h1>
<div class="col-md-12">
<table class="table">
  <tr>
    <th>Nom</th>
    <th>Date</th>
    <th>Etiquettes</th>
    <th>Voir</th>
    <th>Editer</th>
  </tr>
<% @parties.each do |party| %>
  <tr>
    <td><%= party.nom %></td>
    <td><%= party.date.strftime("%F") %></td>
    <td><%= label_duree(party.duree) if party.duree.present? %><%= label_secret(party) %></td>
    <td><%= link_to 'Voir', party_path(party), class: 'btn btn-success btn-xs' %></td>
    <td><%= link_to('Editer', edit_party_path(party), class: 'btn btn-warning btn-xs') %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @parties %>
</div>

app/views/parties/new.html.erb
<h1>Nouvelle partie</h1>

<%= render 'form' %>

app/views/parties/show.html.erb
<h2><%= @party.nom %></h2>
<p id="notice"><%= notice %></p>

<div class="col-md-10">

<p>
  <b>Date:</b>
  <%= @party.date %>
</p>

<p>
  <b>Duree:</b>
  <%= @party.duree %> heures
</p>

<p>
  <b>Xps:</b>
  <%= @party.xps %>
</p>

<% if @user.role == User::ROLE_ADMIN %>
<p>
  <b>Description:</b>
  <%= simple_format @party.description %>
</p>
<% end %>

<p>
  <b>Description publique:</b>
  <%= simple_format @party.description_publique %>
</p>

<% if @user.role == User::ROLE_ADMIN %>
<p>
  <b>Notes:</b>
  <%= simple_format @party.notes %>
</p>
<% end %>

<p>
<b>Membres:</b><br/>
<% if !@membres.nil? %>
  <% @membres.each do |type, group| %>
    <b><%= type ? "Pnjs" : "Joueurs" %></b><br/>
    <% group.each do |mem| %>
      <%= link_to "#{mem.prenom} #{mem.nom}", public_show_personnage_path(mem) %><br/>
    <% end %>
  <% end %>
<% end %>
</p>

<%= link_to 'Editer', edit_party_path(@party), class: 'btn btn-success btn-sm' %>
<%= link_to 'Retour', parties_path, class: 'btn btn-warning btn-sm' %>

</div>