config/routes.rb
Rubricam::Application.routes.draw do

  resources :nodes

  resources :nivarts

  resources :version_comments

  resources :parties

  resources :campagnes

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :users

  root :to => 'accueil#index'
  match '/regles', to: 'accueil#regles'
  match '/fan_art', to: 'accueil#fan_art'
  match '/carte', to: 'accueil#carte'
  match '/navigation', to: 'accueil#navigation'
  match '/cv_elyse_cordeau', to: 'accueil#cv_elyse_cordeau'
  get 'omni_search/search'
  get 'users/omni_search/search'

  resources :arts

  resources :royaumes

  resources :combinaisons

  resources :disciplines

  resources :nivdisciplines

  resources :objets

  resources :routines

  resources :spheres

  resources :lieus

  resources :organisations do
    get :secret_update, on: :member
  end

  resources :historiques

  resources :atouts

  resources :relations do
    get :visuel, on: :collection
  end

  resources :relations_organisations

  resources :capacites

  resources :personnages do
    get :get_infos, on: :collection  #For Ajax test
    get :public_edit, on: :member
    get :public_show, on: :member
    post :public_update, on: :member
    get :routine_edit, on: :member
    post :routine_update, on: :member
    get :discipline_edit, on: :member
    post :discipline_update, on: :member
    get :combinaison_edit, on: :member
    post :combinaison_update, on: :member
    get :pnjs, on: :collection
    get :pjs, on: :collection
    get :reset_xps, on: :member
    get :reset_bonus, on: :member
    get :reset_base, on: :member
    get :background_edit, on: :member
    post :background_update, on: :member
    get :secret_update, on: :member
    get :pnj_update, on: :member
    get :test_update, on: :member
  end

end

app/models/discipline.rb
# == Schema Information
#
# Table name: disciplines
#
#  id             :integer          not null, primary key
#  nom            :string(255)
#  description    :text
#  nom_discipline :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  source         :string(255)
#  secret         :boolean
#  meta_dis       :boolean
#

class Discipline < ActiveRecord::Base
  attr_accessible :description, :nom, :nom_discipline, :source, :secret, :nivdiscipline_ids

  validates_presence_of :description, :nom, :source

  has_and_belongs_to_many :combinaisons, class_name: 'Combinaison'
  has_and_belongs_to_many :personnages, class_name: 'Personnage'
  has_many :nivdisciplines, :class_name => 'Nivdiscipline', :foreign_key => 'discipline_id'

  scope :none_secret, lambda { where("secret = ? or secret is null", false) }
  scope :secret, lambda { where("secret = ?", true) }
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :show]
  before_filter :redirect_unauthorized_to_write, :only=> [:edit, :update, :destroy, :new, :create]

  # GET /disciplines
  # GET /disciplines.json
  def index
    # raise params.inspect
    @disciplines = Discipline.paginate(page: params[:page], per_page: 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disciplines }
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
    @discipline = Discipline.find(params[:id])
    @nivdisciplines = Nivdiscipline.where(discipline_id: @discipline.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discipline }
    end
  end

  # GET /disciplines/new
  # GET /disciplines/new.json
  def new
    @discipline = Discipline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discipline }
    end
  end

  # GET /disciplines/1/edit
  def edit
    @discipline = Discipline.find(params[:id])
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(params[:discipline])

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline a été crée avec succès.' }
        format.json { render json: @discipline, status: :created, location: @discipline }
      else
        format.html { render action: "new" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disciplines/1
  # PUT /disciplines/1.json
  def update
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      if @discipline.update_attributes(params[:discipline])
        format.html { redirect_to @discipline, notice: 'Discipline a été édité avec succès.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy

    respond_to do |format|
      format.html { redirect_to disciplines_url }
      format.json { head :no_content }
    end
  end

  private

  def redirect_unauthorized_to_write
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if !permition_write?(@user)
  end

  def permition_write?(user)
    return true if user.admin?
    false
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= simple_form_for(@discipline) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-5">
    <%= f.input :nom %>
    <%= f.input :nom_discipline %>
    (Si different du nom, ex: Nécromancie et la voie des cendres)
    <%= f.input :description %>
    <%= f.input :source %>
    <%= f.input :secret, label: "Voulez-vous que cette discipline soit secrete ?", wrapper_html: {class: 'inline simple-checkbox'} %>
    <%= f.button :submit, "Créer/Editer une discipline", class: 'btn btn-success btn-sm' %>
    <%= link_to 'Retour', root_path, class: 'btn btn-warning btn-sm' %>
  </div>

  <div class="col-md-5">
    <div class="discipline">
      <label for="search_discipline"> Rechercher niveau discipline :</label>
      <input id="search_discipline" type="text" onkeypress="filter(this, '.discipline .checkbox .check_boxes')" onkeyup="epurationCheckBox(this, '.discipline .checkbox .check_boxes')">
      <%= f.association(:nivdisciplines, as: :check_boxes, :collection => Nivdiscipline.all.map {|c| [c.nom, c.id]}.uniq, wrapper_html: { class: 'col-md-12' }) %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    manageCheckBox("#search_discipline", ".discipline .checkbox .check_boxes");
  });
</script>

app/views/disciplines/edit.html.erb
<h1>Editer une discipline</h1>

<%= render 'form' %>

app/views/disciplines/index.html.erb
<%= link_to 'Nouvelle Discipline', new_discipline_path, class: 'btn btn-success btn-sm create-float' %>
<%= link_to 'Nouveau niveau discipline', new_nivdiscipline_path, class: 'btn btn-info btn-sm create-float' %>
<%= link_to 'Retour', root_url, class: 'btn btn-warning btn-sm create-float' %>
<h1>Liste des disciplines</h1>
<div class="col-md-12">
<table class="table">
  <tr>
    <th>Nom</th>
    <th>Etiquettes</th>
    <th>Voir</th>
    <th>Editer</th>
  </tr>

<% @disciplines.each do |discipline| %>
  <tr>
    <td><%= discipline.nom %></td>
    <td><%= content_tag :span, discipline.source, class: "label label-danger" %><%= label_secret(discipline) %></td>
    <td><%= link_to 'Voir', discipline_path(discipline), class: 'btn btn-success btn-xs' %></td>
    <td><%= link_to('Editer', edit_discipline_path(discipline), class: 'btn btn-warning btn-xs') %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @disciplines %>
</div>

app/views/disciplines/new.html.erb
<h1>Nouvelle discipline</h1>

<%= render 'form' %>

app/views/disciplines/show.html.erb
<h2><%= @discipline.nom %></h2>
<p id="notice"><%= notice %></p>
<div class="col-md-12">

<p>
  <b>Description:</b>
  <%= @discipline.description %>
</p>

<p>
  <% if !@nivdisciplines.nil? %>
    <div>Les niveaux de <%= @discipline.nom %> :</div>
    <table class="table">
      <tr>
        <th>Nom</th>
        <th>Niveau</th>
        <th>Etiquettes</th>
        <th>Voir</th>
      </tr>
    <% @nivdisciplines.each do |nivdiscipline| %>
      <tr>
        <td><%= link_to nivdiscipline.nom, nivdiscipline_path(nivdiscipline) %></td>
        <td><%= label_niveau(nivdiscipline.niveau) %></td>
        <td><%= content_tag :span, nivdiscipline.source, class: "label label-danger" %><%= label_secret(nivdiscipline) %></td>
        <td><%= link_to 'Voir', nivdiscipline_path(nivdiscipline), class: 'btn btn-success btn-xs' %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</p>


<%= link_to 'Editer', edit_discipline_path(@discipline), class: 'btn btn-success btn-sm' %>
<%= link_to 'Retour', disciplines_path, class: 'btn btn-warning btn-sm' %>
</div>