config/routes.rb
Rubricam::Application.routes.draw do

  resources :nodes

  resources :nivarts

  resources :version_comments

  resources :parties

  resources :campagnes

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :users

  root :to => 'accueil#index'
  match '/regles', to: 'accueil#regles'
  match '/fan_art', to: 'accueil#fan_art'
  match '/carte', to: 'accueil#carte'
  match '/navigation', to: 'accueil#navigation'
  match '/cv_elyse_cordeau', to: 'accueil#cv_elyse_cordeau'
  get 'omni_search/search'
  get 'users/omni_search/search'

  resources :arts

  resources :royaumes

  resources :combinaisons

  resources :disciplines

  resources :nivdisciplines

  resources :objets

  resources :routines

  resources :spheres

  resources :lieus

  resources :organisations do
    get :secret_update, on: :member
  end

  resources :historiques

  resources :atouts

  resources :relations do
    get :visuel, on: :collection
  end

  resources :relations_organisations

  resources :capacites

  resources :personnages do
    get :get_infos, on: :collection  #For Ajax test
    get :public_edit, on: :member
    get :public_show, on: :member
    post :public_update, on: :member
    get :routine_edit, on: :member
    post :routine_update, on: :member
    get :discipline_edit, on: :member
    post :discipline_update, on: :member
    get :combinaison_edit, on: :member
    post :combinaison_update, on: :member
    get :pnjs, on: :collection
    get :pjs, on: :collection
    get :reset_xps, on: :member
    get :reset_bonus, on: :member
    get :reset_base, on: :member
    get :background_edit, on: :member
    post :background_update, on: :member
    get :secret_update, on: :member
    get :pnj_update, on: :member
    get :test_update, on: :member
  end

end

app/models/organisation.rb
# == Schema Information
#
# Table name: organisations
#
#  id                   :integer          not null, primary key
#  nom                  :string(255)
#  description          :text
#  type_organisation    :string(255)
#  date                 :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  secret               :boolean
#  description_publique :text
#  image_lien           :string(255)
#  avatar               :string(255)
#

require 'carrierwave/orm/activerecord'

class Organisation < ActiveRecord::Base
  attr_accessible :date, :description, :nom, :type_organisation, :secret,
                  :description_publique, :image_lien, :personnage_ids, :avatar, :avatar_cache

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :nom, :type_organisation, :description

  has_and_belongs_to_many :personnages, class_name: 'Personnage'
  has_and_belongs_to_many :lieus, class_name: 'Lieu'
  has_many :relations_organisation, :class_name => 'RelationsOrganisation', :foreign_key => 'to_organisation_id'
  has_many :relations_organisation, :class_name => 'RelationsOrganisation', :foreign_key => 'from_organisation_id'

  scope :none_secret, lambda { where("secret = ? or secret is null", false) }

  TYPE_ORGANISATION = ["Tradition", "Fondation", "Corporation", "Cabale", "Clan", "Lignée", "Secte", "Coterie", "Autre"]

  def avatar_url_perso
    out = avatar_url.split("/")
    "#{out[0..2].join("/")}/rubricam-avatars/#{out[3..-1].join("/")}"
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  before_filter :redirect_unauthorized_to_show, :only=> [:show]
  before_filter :redirect_unauthorized_to_write, :only=> [:edit, :update, :destroy]

  # GET /organisations
  # GET /organisations.json
  def index
    if @user.role == User::ROLE_ADMIN
      @organisations = Organisation.paginate(page: params[:page], per_page: 20)
    else
      @organisations = Organisation.none_secret.paginate(page: params[:page], per_page: 20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])
    if @user.role == User::ROLE_ADMIN
      @membres = @organisation.personnages
    else
      @membres = @organisation.personnages.none_secret
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if @user.role != User::ROLE_ADMIN
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation a été crée avec succès.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation a été édité avec succès.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def secret_update
    # raise params.inspect
    @organisation = Organisation.find(params[:id])
    @personnage = Personnage.find(params[:personnage_id])
    @organisation_personnage = OrganisationsPersonnages.where(organisation_id: @organisation.id, personnage_id: @personnage.id).first
    if @organisation_personnage.secret
      @organisation_personnage.secret = false 
    else
      @organisation_personnage.secret = true
    end
    @organisation_personnage.save
    redirect_to organisation_path(@organisation)
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :no_content }
    end
  end

  private

  def redirect_unauthorized_to_show
    @organisation = Organisation.find(params[:id])
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if !permition_show?(@user)
  end

  def redirect_unauthorized_to_write
    @organisation = Organisation.find(params[:id])
    return redirect_to root_url, notice: "Vous n'avez pas accès à cette ressource." if !permition_write?(@user)
  end

  def permition_show?(user)
    return true if user.role != User::ROLE_NORMA
    return true if !@organisation.secret
    false
  end

  def permition_write?(user)
    return true if user.role == User::ROLE_ADMIN
    false
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
  def secret_or_note_member(organisation, member)
    organisation_personnage = OrganisationsPersonnages
      .where(organisation_id: organisation.id)
      .where(personnage_id: member.id).first
    if organisation_personnage.secret
      content_tag :span, 'Secret', class: 'label label-success'
    else
      content_tag :span, 'Publique', class: 'label label-default'
    end
  end

  def get_organisation(id)
    begin
      org = Organisation.find(id)
    rescue ActiveRecord::RecordNotFound => e
      org = nil
    end
    org
  end
end

app/views/organisations/_form.html.erb
<%= simple_form_for(@organisation) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-5">
    <%= f.input :nom %>
    <%= f.input :description %>
    <%= f.input :type_organisation, collection: Organisation::TYPE_ORGANISATION %>
    <%= f.input :secret, label: "Voulez-vous que ce cette organisation soit secrète ?", wrapper_html: {class: 'inline simple-checkbox'} %>
    <%= f.button :submit, "Créer/Editer une organisation", class: 'btn btn-success btn-sm' %>
    <%= link_to 'Retour', organisations_path, class: 'btn btn-warning btn-sm' %>
  </div>
  <div class="col-md-5">

    <% url = Rails.env.development? ? @organisation.avatar_url : @organisation.avatar_url_perso if @organisation.avatar? %>
    <%= image_tag(url, class: "avatar") if @organisation.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>

    <%= f.input :description_publique %>
    <%#= f.input :image_lien %>
    <br/>
    <div class="personnage">
      <label for="search_personnage"> Rechercher personnage :</label>
      <input id="search_personnage" type="text" onkeypress="filter(this, '.personnage .checkbox .check_boxes')" onkeyup="epurationCheckBox(this, '.personnage .checkbox .check_boxes')">
      <%= f.association(:personnages, as: :check_boxes, :collection => Personnage.all.map {|c| ["#{c.prenom} #{c.nom}", c.id]}.uniq, label: false, wrapper_html: { class: 'col-md-12' }) %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    manageCheckBox("#search_personnage", ".personnage .checkbox .check_boxes");
  });
</script>

app/views/organisations/edit.html.erb
<h1>Edtier une organisation</h1>

<%= render 'form' %>

app/views/organisations/index.html.erb
<%= link_to 'Nouvelle organisation', new_organisation_path, class: 'btn btn-success btn-sm create-float' %>
<%= link_to 'Retour', root_path, class: 'btn btn-warning btn-sm create-float' %>
<h1>Liste des organisations</h1>
<div class="col-md-12">
<table class="table">
  <tr>
    <th>Nom</th>
    <th>Etiquettes</th>
    <th>Voir</th>
    <th>Editer</th>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= organisation.nom %></td>
    <td><%= content_tag :span, organisation.type_organisation, class: "label label-danger" %><%= label_secret(organisation) %></td>
    <td><%= link_to 'Voir', organisation_path(organisation), class: 'btn btn-success btn-xs' %></td>
    <td><%= link_to('Editer', edit_organisation_path(organisation), class: 'btn btn-warning btn-xs') %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @relations %>
</div>

app/views/organisations/new.html.erb
<h1>Nouvelle organisation</h1>

<%= render 'form' %>

app/views/organisations/show.html.erb
<h2><%= @organisation.nom %></h2>
<p id="notice"><%= notice %></p>
<div class="col-md-6">
<% if @user.role == User::ROLE_ADMIN %>
  <p>
    <b>Description:</b>
    <%= simple_format @organisation.description %>
  </p>
<% end %>
<p>
  <b>Description publique:</b>
  <%= simple_format @organisation.description_publique %>
</p>
<p>
  <b>Type:</b>
  <%= @organisation.type_organisation %>
</p>

<p>
  <b>Date:</b>
  <%= @organisation.date %>
</p>

<p>
<b>Membres:</b><br/>
<% if !@membres.nil? %>
  <table class="table">
  <tr>
    <th>Nom</th>
    <% if @user.role == User::ROLE_ADMIN %>
      <th>Changement</th>
      <th>Etat</th>
    <% end %>
  </tr>
  <% @membres.each do |membre| %>
    <tr>
      <td>
        <% if @user.role == User::ROLE_ADMIN %>
          <%= link_to "#{membre.prenom} #{membre.nom}", personnage_path(membre) %><br/>
        <% else %>
          <%= link_to "#{membre.prenom} #{membre.nom}", public_show_personnage_path(membre) %><br/>
        <% end %>
      </td>
      <% if @user.role == User::ROLE_ADMIN %>
        <td>
          <%= link_to 'Secret/Publique', secret_update_organisation_path(id: @organisation.id, personnage_id: membre.id), class: 'btn btn-primary btn-xs' %>
        </td>
        <td>
          <%= secret_or_note_member(@organisation, membre) %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </table>
<% end %>
</p>


<%= link_to 'Editer', edit_organisation_path(@organisation), class: 'btn btn-success btn-sm' %>
<%= link_to 'Retour', organisations_path, class: 'btn btn-warning btn-sm' %>
</div>

<div class="col-md-4">
  <% url = Rails.env.development? ? @organisation.avatar_url : @organisation.avatar_url_perso if @organisation.avatar? %>
  <%= image_tag(url, class: "avatar") if @organisation.avatar? %>
</div>