config/routes.rb
Rubricam::Application.routes.draw do

  resources :nodes

  resources :nivarts

  resources :version_comments

  resources :parties

  resources :campagnes

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :users

  root :to => 'accueil#index'
  match '/regles', to: 'accueil#regles'
  match '/fan_art', to: 'accueil#fan_art'
  match '/carte', to: 'accueil#carte'
  match '/navigation', to: 'accueil#navigation'
  match '/cv_elyse_cordeau', to: 'accueil#cv_elyse_cordeau'
  get 'omni_search/search'
  get 'users/omni_search/search'

  resources :arts

  resources :royaumes

  resources :combinaisons

  resources :disciplines

  resources :nivdisciplines

  resources :objets

  resources :routines

  resources :spheres

  resources :lieus

  resources :organisations do
    get :secret_update, on: :member
  end

  resources :historiques

  resources :atouts

  resources :relations do
    get :visuel, on: :collection
  end

  resources :relations_organisations

  resources :capacites

  resources :personnages do
    get :get_infos, on: :collection  #For Ajax test
    get :public_edit, on: :member
    get :public_show, on: :member
    post :public_update, on: :member
    get :routine_edit, on: :member
    post :routine_update, on: :member
    get :discipline_edit, on: :member
    post :discipline_update, on: :member
    get :combinaison_edit, on: :member
    post :combinaison_update, on: :member
    get :pnjs, on: :collection
    get :pjs, on: :collection
    get :reset_xps, on: :member
    get :reset_bonus, on: :member
    get :reset_base, on: :member
    get :background_edit, on: :member
    post :background_update, on: :member
    get :secret_update, on: :member
    get :pnj_update, on: :member
    get :test_update, on: :member
  end

end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:cv_elyse_cordeau]

  def index
    @personnages = Personnage.own_personnages(@user.id).order("created_at desc").limit(10)
    @pnjs = Personnage.none_secret_and_pnjs.limit(10)
    @historiques = Historique.order('created_at DESC').limit(10)
    @atouts = Atout.none_secret.order('created_at DESC').limit(10)
    @disciplines = Discipline.none_secret.order('created_at DESC').limit(10)
    @capacites = Capacite.order('created_at DESC').limit(10)
  end

  def carte
    @lieux_villes = Lieu
      .includes(:organisations, :personnages, :nodes)
      .locatable
      .lieu_ou_ville
  end

  def navigation
    
  end

  def cv_elyse_cordeau
    File.open('app/views/accueil/cv_elyse_cordeau.pdf', 'r') do |f|
      send_data f.read.force_encoding('BINARY'), :filename => "cv_elyse_cordeau.pdf", :type => "application/pdf", :disposition => "attachment"
    end
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
  def menu_accueil(tab, name_objet, list, titre)
    out = "<div id=\"menu-#{name_objet}\" class=\"menu-accueil\">".html_safe
    out << "<div class=\"menu-accueil-head\">".html_safe
    out << "10 derniers #{titre}".html_safe
    out << "</div>".html_safe
    out << "<div class=\"menu-accueil-body\">".html_safe
      if !list.nil? && list != []
        out << "<table>".html_safe
          out << "<tr>".html_safe
            tab.each do |val|
              out << "<th>#{val}</th>".html_safe
            end
            out << "<th>Voir</th>".html_safe
          out << "</tr>".html_safe
          list.each do |a|
            out << "<tr>".html_safe
              tab.each do |val|
                out << "<td>#{a.send(val)}</td>".html_safe
              end
              if titre != "pnjs"
                out << "<td>#{link_to "Voir", a, class: 'btn btn-success btn-xs'}</td>".html_safe
              else
                out << "<td>#{link_to "Voir", public_show_personnage_path(a), class: 'btn btn-success btn-xs'}</td>".html_safe
              end
            out << "</tr>".html_safe
          end
        out << "</table>".html_safe
      end
    out << "</div>".html_safe
    out << "<div class=\"menu-accueil-action\">".html_safe
      if titre != "pnjs"
        out << link_to("Les #{titre}", send("#{name_objet}_path"), class: 'btn btn-primary btn-sm')
      else
        out << link_to("Les #{titre}", send("pnjs_#{name_objet}_path"), class: 'btn btn-primary btn-sm')
      end
    out << "</div>".html_safe
    out << "</div>".html_safe
    out
  end
end

app/views/accueil/carte.html.erb
<h2></h2>
<div style="text-align: center;"><span class="h2-perso">Carte </span><span class='label label-warning'>Beta</span></div>
<div class="col-md-8">
	<div id="world-map">
		<!-- Created with Inkscape (http://www.inkscape.org/) -->
		<!-- width="2320" height="1200" -->
		<%= render 'carte_v2' %>
	</div>
</div>
<div id="list-data-lieux" class="col-md-4">
	<div style="text-align: center;">Informations lieu</div><br/>
	<div class="partie-personnage small-font">
    	Cliquez sur un lieu en vert pour voir les informations du lieu.
   	</div><br />
</div>
<script>
	init_map(<%= raw @lieux_villes.to_json(include: [:organisations, :personnages, :nodes]) %>, <%= raw @user.to_json %>);
	managerDataLieu();
</script>

app/views/accueil/fan_art.html.erb
<div class="col-md-12">
  <%= image_tag("carte_camille_1.png") %>
  <%= image_tag("carte_camille_2.png") %>
</div>

app/views/accueil/index.html.erb
<h1></h1>
<p id="notice"><%= notice %></p>
<div class="col-md-6">
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      Vos 10 derniers personnages
    </div>
    <div class="menu-accueil-body">
      <% if @personnages != nil %>
        <table>
          <tr>
            <th>Personnage</th>
            <th>Appartenance</th>
            <th>Rang</th>
            <th>Voir</th>
          </tr>
          <% @personnages.each do |p| %>
            <tr>
              <td><%= "#{p.prenom} #{p.nom}" %></td>
              <td style="text-align: center;"><span class="wod"><%= p.symbole_appartenance %></span></td>
              <td><%= label_rang(p) %></td>
              <td><%= link_to "Profil", p, class: 'btn btn-success btn-xs' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Vous n'avez pas de personnages.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Tous vos personnages', personnages_path, class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Créer un personnage', new_personnage_path, class: 'btn btn-success btn-sm' %>
    </div>
  </div>
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      10 dernières capacités
    </div>
    <div class="menu-accueil-body">
      <% if @capacites != nil %>
        <table>
          <tr>
            <th>Nom</th>
            <th>Etiquettes</th>
            <th>Voir</th>
          </tr>
          <% @capacites.each do |capacite| %>
            <tr>
              <td><%= link_to capacite.nom, capacite %></td>
              <td>
                <%= content_tag :span, capacite.source, class: "label label-danger" %><%= content_tag :span, capacite.type_cap, class: 'label label-info' %><%= content_tag :span, capacite.primaire ? 'Primaire' : 'Secondaire', class: 'label label-default' %>
              </td>
              <td><%= link_to 'Voir', capacite_path(capacite), class: 'btn btn-success btn-xs' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Il n'y a pas de capacités.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Toutes les capacités', capacites_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      10 derniers historiques
    </div>
    <div class="menu-accueil-body">
      <% if @historiques != nil %>
        <table>
          <tr>
            <th>Nom</th>
            <th>Etiquettes</th>
            <th>Voir</th>
          </tr>
          <% @historiques.each do |historique| %>
            <tr>
              <td><%= link_to historique.nom, historique %></td>
              <td>
                <%= content_tag :span, historique.source, class: "label label-danger" %><%= content_tag :span, 'Détail', class: 'label label-info' if historique.has_detail %>
              </td>
              <td><%= link_to 'Voir', historique_path(historique), class: 'btn btn-success btn-xs' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Il n'y a d'historiques.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Toutes les capacités', historiques_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      10 derniers Pnjs
    </div>
    <div class="menu-accueil-body">
      <% if @pnjs != nil %>
        <table>
          <tr>
            <th>Personnage</th>
            <th>Appartenance</th>
            <th>Rang</th>
          </tr>
          <% @pnjs.each do |p| %>
            <tr>
              <td><%= p.nom_publique ? p.nom_publique : "#{p.prenom} #{p.nom}" %></td>
              <td style="text-align: center;"><span class="wod"><%= p.symbole_appartenance_publique %></span></td>
              <td><%= label_rang_publique(p) %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Il n'y a pas de Pnjs.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Tous les Pnjs', pnjs_personnages_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      10 derniers atouts
    </div>
    <div class="menu-accueil-body">
      <% if @atouts != nil %>
        <table>
          <tr>
            <th>Nom</th>
            <th>Cout</th>
            <th>Etiquettes</th>
            <th>Voir</th>
          </tr>
          <% @atouts.each do |atout| %>
            <tr>
              <td><%= link_to atout.nom, atout %></td>
              <td><%= atout.cout %></td>
              <td>
                <%= content_tag :span, atout.source, class: "label label-danger" %><%= content_tag :span, 'Détail', class: 'label label-info' if atout.has_detail %><%= content_tag :span, atout.type_atout, class: 'label label-default' %><%= content_tag :span, atout.cout > 0 ? 'Avantage' : 'Handicap', class: 'label label-warning' %>
              </td>
              <td><%= link_to 'Voir', atout_path(atout), class: 'btn btn-success btn-xs' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Il n'y a pas d'atouts.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Tous les atouts', atouts_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
  <div id="menu-personnages" class="menu-accueil">
    <div class="menu-accueil-head">
      10 dernières disciplines
    </div>
    <div class="menu-accueil-body">
      <% if @disciplines != nil %>
        <table>
          <tr>
            <th>Nom</th>
            <th>Etiquettes</th>
            <th>Voir</th>
          </tr>
          <% @disciplines.each do |discipline| %>
            <tr>
              <td><%= link_to discipline.nom, discipline %></td>
              <td><%= content_tag :span, discipline.source, class: "label label-danger" %><%= label_secret(discipline) %></td>
              <td><%= link_to 'Voir', discipline_path(discipline), class: 'btn btn-success btn-xs' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        Il n'y a pas de disciplines.
      <% end %>
    </div>
    <div class="menu-accueil-action">
      <%= link_to 'Tous les disciplines', disciplines_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
</div>

app/views/accueil/navigation.html.erb
<h1></h1>
<%#= link_to 'Accueil', root_url, class: 'btn btn-success btn-sm' %>
<%#= link_to 'Navigation', navigation_path, class: 'btn btn-success btn-sm' %>
<%#= link_to 'Disciplines', disciplines_path, class: 'btn btn-info btn-sm' %>
<%#= link_to 'Combinaisons de discipline', combinaisons_path, class: 'btn btn-success btn-sm' %>
<%#= link_to 'Atouts', atouts_path, class: 'btn btn-primary btn-sm' %>
<%#= link_to 'Historiques', historiques_path, class: 'btn btn-warning btn-sm' %>
<%#= link_to 'Capacités', capacites_path, class: 'btn btn-danger btn-sm' %>
<%#= link_to 'Règles', regles_path, class: 'btn btn-success btn-sm' %>
<%# if @user.id.present? %>
  <%#= link_to 'Routines', routines_path, class: 'btn btn-success btn-sm' %>
  <%#= link_to 'Objets', objets_path, class: 'btn btn-info btn-sm' %>
  <%#= link_to 'Personnages', personnages_path, class: 'btn btn-primary btn-sm' %>
  <%#= link_to 'Lieux', lieus_path, class: 'btn btn-warning btn-sm' %>
  <%#= link_to 'Organisations', organisations_path, class: 'btn btn-info btn-sm' %>
  <%#= link_to 'Pnjs', pnjs_personnages_path, class: 'btn btn-success btn-sm' %>
  <%#= link_to 'Parties', parties_path, class: 'btn btn-warning btn-sm' %>
  <%#= link_to 'Pjs', pjs_personnages_path, class: 'btn btn-info btn-sm' %>
  <%#= link_to 'Carte', carte_path, class: 'btn btn-danger btn-sm' %>
<%# end %>
<%# if @user.role == User::ROLE_ADMIN %>
  <%#= link_to 'Joueurs', users_path, class: 'btn btn-success btn-sm' %>
<%# end %>
<%#= link_to 'Royaume', fan_art_path, class: 'btn btn-info btn-sm' %>
<%#= link_to 'Se déconnecter', destroy_user_session_path, :method => :delete, class: 'btn btn-danger btn-sm' %></li>
<div class="col-md-12">
  <div id="mynetwork"></div>
</div>
<script type="text/javascript">
  // create an array with nodes
  var menus = [
    {id: 0, label: "Rubricam", group: 0},
    {id: 1, label: "Accueil", group: 1},
    {id: 2, label: "Navigation", group: 1},
    {id: 3, label: "Wiki", group: 1},
    {id: 4, label: "Partie", group: 1},
    {id: 5, label: "Mj", group: 1},
    {id: 6, label: "Disciplines", group: 2},
    {id: 7, label: "Combinaisons de discipline", group: 2},
    {id: 8, label: "Atouts", group: 2},
    {id: 9, label: "Historiques", group: 2},
    {id: 10, label: "Capacités", group: 2},
    {id: 11, label: "Règles", group: 2},
    {id: 12, label: "Objets", group: 3},
    {id: 13, label: "Personnages", group: 3},
    {id: 14, label: "Lieux", group: 3},
    {id: 15, label: "Organisations", group: 3},
    {id: 16, label: "Pnjs", group: 3},
    {id: 17, label: "Parties", group: 3},
    {id: 18, label: "Pjs", group: 3},
    {id: 19, label: "Carte", group: 3},
    {id: 20, label: "Joueurs", group: 4},
    {id: 21, label: "Royaume", group: 1},
  ]

  var refs = ["","","","","","","disciplines","combinaisons","atouts","historiques","capacites","regles","objets","personnages","lieus","organisations","personnages/pnjs","parties","personnages/pjs","carte","joueurs","fan_art"]

  var nodes = new vis.DataSet(menus);

  // create an array with edges
  var edges = new vis.DataSet([
    {from: 0, to: 1},
    {from: 0, to: 2},
    {from: 0, to: 3},
    {from: 0, to: 4},
    {from: 0, to: 5},
    {from: 3, to: 6},
    {from: 3, to: 7},
    {from: 3, to: 8},
    {from: 3, to: 9},
    {from: 3, to: 10},
    {from: 3, to: 11},
    {from: 4, to: 12},
    {from: 4, to: 13},
    {from: 4, to: 14},
    {from: 4, to: 15},
    {from: 4, to: 16},
    {from: 4, to: 17},
    {from: 4, to: 18},
    {from: 4, to: 19},
    {from: 5, to: 20},
    {from: 0, to: 21}
  ]);

  // create a network
  var container = document.getElementById('mynetwork');
  var data = {
    nodes: nodes,
    edges: edges
  };
  var options = {
    nodes: {
      fixed: true
    },
    edges: {
      smooth: false
    },
    interaction: {
      dragView: false,
      zoomView: false
    },
    physics: {
      enabled: false,
      minVelocity: 0.75
    }
  };
  var network = new vis.Network(container, data, options);

  network.on("doubleClick", function (params) {
    window.location.replace($(location).attr('protocol')+"//"+$(location).attr('host')+"/"+refs[params["nodes"][0]]);
  });
</script>

app/views/accueil/prime.html.erb
<h2></h2>
<p id="notice"><%= notice %></p>
<div id="prime" class="col-md-4">
  <div class="menu-accueil">
    <div class="menu-accueil-head">
      <% if @version.present? %>
        <div style="text-align: center;">
          Rubricam v<%= @version.version %>.<%= @version.subversion %>
          <%= link_to "(Détail)", version_comment_path(@version) %>
        </div>
        <%= simple_format @version.content %>
      <% end %>
    </div>
    <div class="menu-accueil-body">
      <div style="text-align: center;"><b>Avancement du Wiki</b></div>
      <div class="progress">
  	    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
  	    	V20
  	  	</div>
    	</div>
    	<div class="progress">
  	  	<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width: 15%;">
  	    	M20
  	  	</div>
    	</div>
      <div class="progress">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width: 15%;">
          W20
        </div>
      </div>
    </div>
    <div class="menu-accueil-action"></div>
  </div>
</div>
<div class="col-md-5">
  <div class="menu-accueil">
    <div class="menu-accueil-head" style="text-align: center;"><b><%= @faction_name %></b></div>
    <div class="row menu-accueil-body">
      <div class="col-md-3">
        <%= image_tag("wod/#{@image_link}.png", class: "") if Rails.application.assets.find_asset("wod/#{@image_link}.png").present? %>
      </div>
      <div class="col-md-9">
        <%= @faction %>
      </div>
    </div>
    <div class="menu-accueil-action"></div>
  </div>

</div>

app/views/accueil/regles.html.erb
<h2>Règles supplémentaires</h2>
<div class="col-md-6">
  <b>Magie dynamique</b>

  <br/><b><i>Niveau de protection maximum possible :</i></b>
  Le niveau de protection maximum d’une routine (Voir Lexique en bas du document) est égal à 5 avec 2 dans la sphère en question, 8 avec 4 dans la sphère en question, 12 avec 5.

  <br/><b><i>Nombre de succès maximum possible :</i></b>
  Le nombre de succès maximum cumulable possible pour une routine est égal au score d'entéléchie multipliée par la volonté du mage.

  <br/><b><i>Difficulté des puissants rituels :</i></b>
  Quand le mage effectue une routine (on parle ici de rituels) dont le nombre de succès dépasse les 2/3 de son nombre de succès maximum possible, cette routine devra s’accompagner d’un quelconque foci supplémentaire. Qui prendra des formes variés en fonction du paradigme du mage mais ce foci doit dans tous les cas être plus difficile à réaliser/se procurer que les foci courant du mage.

  <br/><b><i>Modificateur maximal :</i></b>
  Le modificateur maximal passe à +/- 5 au lieu de +/- 3. La difficulté minimal et maximal reste la même (respectivement 3 et 9). L'ensemble des autres règles à ce sujet reste les mêmes.

  <br/><b><i>Routine et volonté :</i></b>
  Si une routine doit influencer la psyché d’un individu la cible doit réussir un jet de volonté (SR variable, souvent 6 ou 7) avec autant de succès que l'efficacité de ladite routine.

  <br/><b><i>Niveau de protection similaire :</i></b>
  C’est le plus haut niveau de protection qui est pris en compte.

  <br/><b><i>Cibles supplémentaires :</i></b>
  La règle sur les cibles supplémentaires restent la même que dans le livre de règle sauf en ce qui concerne les effets durant plus d’une scène. Dans ce cas précis le nombre de succès supplémentaire nécessaire est égal a la somme des nombres compris entre un et le nombres de cibles supplémentaires. Par exemple : pour un sort affectant trois cibles supplémentaires, le nombre de succès nécessaires pour affecter ces trois cibles est de six.

  <br/><br/><b>Lexique</b>

  <br/><b><i>Niveau de protection.</i></b>
  Un mage possédant un protection contre une sphère (Comme avec un effet de deuxième niveau de sphère), sous forme d’enchantement par exemple bénéficie d’un niveau de protection égal au nombre de succès alloués a l'efficacité. Un niveau de protection retire un succès au test d'entéléchie.
</div>
<div class="col-md-6">
  <b>Les interactions entre la magie dynamique et les disciplines vampiriques</b>

  <br/><b><i>Effet protecteur de magie vampirique contre un effet offensif de magie dynamique :</i></b>
  Le vampire bénéficie d’un niveau de protection virtuel égal à la moitié du niveau de son pouvoir de protection vampirique (arrondie au supérieur, le plus haut niveau de discipline dans le cas d’une combinaison de discipline, le niveau du pouvoir de la discipline dans le cas d’une protection issus d’une discipline ou le niveau du rituel protecteur dans le cas d’un rituel). Si on obtient une égalité, il faut effectuer un jet de volonté en opposition.

  <br/><b><i>Effet protecteur de magie dynamique contre un effet offensif de magie vampirique :</i></b>
  Si le niveau de la discipline vampirique offensif est supérieur au niveau de protection du mage, l’effet vampirique peut fonctionner correctement (Si l’effet du pouvoir vampirique nécessite des jets de dés, ils doivent être effectuées normalement). Si le niveau de discipline vampirique offensif est inférieur au niveau de protection du mage, l’effet vampirique échoue. Si le niveau de la discipline vampirique est égal au niveau de protection du mage, il faut effectuer un jet de volonté en opposition.
  Dans le cas où un jet de dés doit être effectués et que le vampire obtient un nombre de succès au moins égal au double du niveau de la protection du mage, l'effet vampirique fonctionne correctement (même s'il ne devrait normalement pas fonctionner en suivant la première règle).

  <br/><b><i>Contremagie dynamique contre un effet de magie vampirique :</i></b>
  Si le mage obtient un nombre de succès supérieur à son test de contremagie égale à la moitié du niveau de son pouvoir vampirique (arrondie au supérieure) il annule l’effet de magie vampirique. Si le mage obtient moins de succès à son test de contremagie, il n’arrive pas à contrer l’effet vampirique. En cas d’égalité, il faut effectuer un jet de volonté en opposition.

  <br/><br/><b>Autres</b>

  <br/><b><i>Armure/Protection multiples :</i></b>
  Si un individu possède plusieurs protection, tous les malus se cumulent. Seule la plus grande armure/protection est prise en compte. Par contre le seuil est réduit d’un point par armure/protection supplémentaire efficaces contre le même type d’attaque.
  <br/><b><i>Protection antimagique multiples :</i></b>
  Si un individu possède plusieurs protection, seule la plus grande protection est prise en compte. Par contre le seuil est réduit d’un point par protection supplémentaire efficaces contre le même type d’attaque.
  <br/><b><i>Points d’expérience pour les Mages :</i></b>
  J’utiliserai la règle de base sur les points d’expérience de Mage. C’est-à-dire que c’est toujours le niveau supérieure multipliée par une constante (huit pour les sphères par exemple).
  <br/><b><i>Capacités secondaires :</i></b>
  Les capacités dites secondaires (déterminés par le conteur) coûte seulement niveau à atteindre en expérience (Que ce soit pour les mages ou les vampires). Un point bonus donne deux points de capacités secondaires ou un point de capacité secondaire pour les niveaux supérieurs à trois.
</div>